//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileTransferRequest", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    public partial class FileTransferRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] ContentField;
        
        private string FileNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MunicipalityTaxResponse", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    public partial class MunicipalityTaxResponse : WCF_Service.MunicipalityTax
    {
        
        private string MessageField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MunicipalityTax", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCF_Service.MunicipalityTaxResponse))]
    public partial class MunicipalityTax : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MunicipalityField;
        
        private decimal TaxField;
        
        private string TaxTypeField;
        
        private System.DateTime ValidFromField;
        
        private System.DateTime ValidToField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Municipality
        {
            get
            {
                return this.MunicipalityField;
            }
            set
            {
                this.MunicipalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tax
        {
            get
            {
                return this.TaxField;
            }
            set
            {
                this.TaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxType
        {
            get
            {
                return this.TaxTypeField;
            }
            set
            {
                this.TaxTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidFrom
        {
            get
            {
                return this.ValidFromField;
            }
            set
            {
                this.ValidFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidTo
        {
            get
            {
                return this.ValidToField;
            }
            set
            {
                this.ValidToField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralResponse", Namespace="http://schemas.datacontract.org/2004/07/WCF_Service")]
    public partial class GeneralResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string messageField;
        
        private bool statusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITaxManagement")]
public interface ITaxManagement
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxManagement/UploadDataFromFile", ReplyAction="http://tempuri.org/ITaxManagement/UploadDataFromFileResponse")]
    WCF_Service.MunicipalityTaxResponse[] UploadDataFromFile(WCF_Service.FileTransferRequest req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxManagement/UploadDataFromFile", ReplyAction="http://tempuri.org/ITaxManagement/UploadDataFromFileResponse")]
    System.Threading.Tasks.Task<WCF_Service.MunicipalityTaxResponse[]> UploadDataFromFileAsync(WCF_Service.FileTransferRequest req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxManagement/GetTaxTypes", ReplyAction="http://tempuri.org/ITaxManagement/GetTaxTypesResponse")]
    string[] GetTaxTypes();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxManagement/GetTaxTypes", ReplyAction="http://tempuri.org/ITaxManagement/GetTaxTypesResponse")]
    System.Threading.Tasks.Task<string[]> GetTaxTypesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxManagement/GetTaxInfo", ReplyAction="http://tempuri.org/ITaxManagement/GetTaxInfoResponse")]
    WCF_Service.MunicipalityTaxResponse GetTaxInfo(WCF_Service.MunicipalityTax req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxManagement/GetTaxInfo", ReplyAction="http://tempuri.org/ITaxManagement/GetTaxInfoResponse")]
    System.Threading.Tasks.Task<WCF_Service.MunicipalityTaxResponse> GetTaxInfoAsync(WCF_Service.MunicipalityTax req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxManagement/AddTaxRecord", ReplyAction="http://tempuri.org/ITaxManagement/AddTaxRecordResponse")]
    WCF_Service.GeneralResponse AddTaxRecord(WCF_Service.MunicipalityTax tbl);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxManagement/AddTaxRecord", ReplyAction="http://tempuri.org/ITaxManagement/AddTaxRecordResponse")]
    System.Threading.Tasks.Task<WCF_Service.GeneralResponse> AddTaxRecordAsync(WCF_Service.MunicipalityTax tbl);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxManagement/UpdateTaxRecord", ReplyAction="http://tempuri.org/ITaxManagement/UpdateTaxRecordResponse")]
    WCF_Service.GeneralResponse UpdateTaxRecord(WCF_Service.MunicipalityTax tbl);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxManagement/UpdateTaxRecord", ReplyAction="http://tempuri.org/ITaxManagement/UpdateTaxRecordResponse")]
    System.Threading.Tasks.Task<WCF_Service.GeneralResponse> UpdateTaxRecordAsync(WCF_Service.MunicipalityTax tbl);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITaxManagementChannel : ITaxManagement, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TaxManagementClient : System.ServiceModel.ClientBase<ITaxManagement>, ITaxManagement
{
    
    public TaxManagementClient()
    {
    }
    
    public TaxManagementClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TaxManagementClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TaxManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TaxManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WCF_Service.MunicipalityTaxResponse[] UploadDataFromFile(WCF_Service.FileTransferRequest req)
    {
        return base.Channel.UploadDataFromFile(req);
    }
    
    public System.Threading.Tasks.Task<WCF_Service.MunicipalityTaxResponse[]> UploadDataFromFileAsync(WCF_Service.FileTransferRequest req)
    {
        return base.Channel.UploadDataFromFileAsync(req);
    }
    
    public string[] GetTaxTypes()
    {
        return base.Channel.GetTaxTypes();
    }
    
    public System.Threading.Tasks.Task<string[]> GetTaxTypesAsync()
    {
        return base.Channel.GetTaxTypesAsync();
    }
    
    public WCF_Service.MunicipalityTaxResponse GetTaxInfo(WCF_Service.MunicipalityTax req)
    {
        return base.Channel.GetTaxInfo(req);
    }
    
    public System.Threading.Tasks.Task<WCF_Service.MunicipalityTaxResponse> GetTaxInfoAsync(WCF_Service.MunicipalityTax req)
    {
        return base.Channel.GetTaxInfoAsync(req);
    }
    
    public WCF_Service.GeneralResponse AddTaxRecord(WCF_Service.MunicipalityTax tbl)
    {
        return base.Channel.AddTaxRecord(tbl);
    }
    
    public System.Threading.Tasks.Task<WCF_Service.GeneralResponse> AddTaxRecordAsync(WCF_Service.MunicipalityTax tbl)
    {
        return base.Channel.AddTaxRecordAsync(tbl);
    }
    
    public WCF_Service.GeneralResponse UpdateTaxRecord(WCF_Service.MunicipalityTax tbl)
    {
        return base.Channel.UpdateTaxRecord(tbl);
    }
    
    public System.Threading.Tasks.Task<WCF_Service.GeneralResponse> UpdateTaxRecordAsync(WCF_Service.MunicipalityTax tbl)
    {
        return base.Channel.UpdateTaxRecordAsync(tbl);
    }
}
